[build]
  command = "npm run bundle && npm run build"
  functions = "/netlify/functions"
  publish = "build"

[[redirects]]
  from = "/express-starter"
  to = "/.netlify/functions/express-starter"
  status = 200